const allData = {
  contactListData: [
    {
      id: 1,
      name: "Jane Doe",
      text: "Hi, I want to make enquiries about your product",
      hasRead: false,
      isOnline: true,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (1).png",
    },
    {
      id: 2,
      name: "Janet Adebayo",
      text: "Hi, I want to make enquiries about your product",
      hasRead: false,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (2).png",
    },
    {
      id: 3,
      name: "Kunle Adekunle",
      text: "Hi, I want to make enquiries about your product",
      hasRead: false,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (3).png",
    },
    {
      id: 4,
      name: "Jane Doe",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: true,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (1).png",
    },
    {
      id: 5,
      name: "Janet Adebayo",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (2).png",
    },
    {
      id: 6,
      name: "Kunle Adekunle",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (3).png",
    },
    {
      id: 7,
      name: "Jane Doe",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: true,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (1).png",
    },
    {
      id: 8,
      name: "Janet Adebayo",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (2).png",
    },
    {
      id: 9,
      name: "Kunle Adekunle",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (3).png",
    },
    {
      id: 10,
      name: "Jane Doe",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: true,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (1).png",
    },
    {
      id: 11,
      name: "Janet Adebayo",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (2).png",
    },
    {
      id: 12,
      name: "Kunle Adekunle",
      text: "Hi, I want to make enquiries about your product",
      hasRead: true,
      isOnline: false,
      timeStamp: "12:55am",
      profileImg: "/images/Rectangle 3 (3).png",
    },
  ],
};

export default allData;
